Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainParameter:
    Description: apex domain
    Type: String

Resources:
  ProxyEntryLambdaFunction: #logical ID
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src
      Handler: index.handler
      Role: !GetAtt ProxyEntryRole.Arn
      Environment:
        Variables:
          ORIGINMAP_TABLE: !Ref OriginMapTBL
          DOMAIN: !Ref DomainParameter

ProxyEntryRole: #name of resource
  Type: AWS::IAM::Role #IAM
  Properties:
    Path: /
    RoleName: stack-proxy-proxyentry-role #Name
    AssumeRolePolicyDocument: #Trust policies define which entities can assume the role
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com #Lambda has permission
          Action: sts.AssumeRole
    #Lambda can do "Policies"
    #Lambda has access to logs; create and put
    #Lambda has access to dynamodb; all actions
    Policies:
      - PolicyName: stack-proxy-proxyentry-role
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws::logs:*:*:*
            - Effect: Allow
              Action:
                - dynamodb:*
              Resource:
                - !Sub arn:aws:${AWS::Region}:${AWS::AccountId}:table/stack-proxy-*
                - !Sub arn:aws:${AWS::Region}:${AWS::AccountId}:table/stack-proxy-*/index/*

OriginMapTBL: #name of resource
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: stack-proxy-domainmap
    AttributeDefinitions:
      - AttributeName: Host
        AttributeType: S
    KeySchema:
      - AttributeName: Host
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

Outputs:
  ProxyEntryLambdaARN:
    Description: ProxyEntry Lambda ARN
    Value: !GetAtt ProxyEntryLambdaFunction.Arn
    Export:
      Name: stack-proxy-proxyentry-lambda-arn
