Parameters:
  ServiceParameter:
    Type: String
    Description: Service name
  StageParameter:
    Type: String
    Default: dev
    Description: Feature branch

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
  ProxyEntry:
    Type: Custom::ProxyEntry
    Version:  1.0
    Properties:
      ServiceToken: !ImportValue stack-proxy-proxyentry-lambda-arn
      Service: !Ref ServiceParameter
      Stage: !Ref StageParameter
      Origin: !GetAtt WebsiteBucket.DomainName

Outputs:
  SiteURL:
    Description: URL for this Site
    Value: !Sub https://${ProxyEntry.Host}
